config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]  
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: [:index, :new]
  end
  resources :albums

  root to: redirect('/bands')


end

app/models/album.rb
class Album < ApplicationRecord
    validates :band_name, :title, :year, presence: true
    
    belongs_to :band,
        foreign_key: :band_name

    has_many :tracks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord

    validates :name, presence: true

    has_many :albums,
        foreign_key: :band_name

    has_many :tracks,
        through: :albums,
        source: :tracks




end

app/models/track.rb
class Track < ApplicationRecord

    validates :title, :ord, presence: true


    belongs_to :album

end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true

    attr_reader :password

    after_initialize :ensure_session_token
    #PREFIG
    def password=(passkey)
        @password = passkey
        self.password_digest = BCrypt::Password.create(passkey) 
    end
   

    def self.find_by_credentials(email, password)
        u = User.find_by(email: email)
        return nil if u.nil?
        u.is_password?(password) ? u : nil
    end

    def reset_session_token!
        self.generate_session_token
        self.save!
        self.session_token
    end

    

    def generate_session_token
        self.session_token = SecureRandom.urlsafe_base64(16)
    end

    def is_password?(passkey)
        BCrypt::Password.new(self.password_digest).is_password?(passkey)
    end

    private


    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64(16)
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController



    def index
        debugger
        if params.has_key?(:band_id)
            @albums = Album.where(band_name: params[:band_id])
        else
            @albums = Album.all
        end
        render :index
    end

    def new
        @album = Album.new
        render :new
    end

    def create
        debugger
        @album = Album.new(album_params)
        if @album.save
            redirect_to band_url(@album.band_name)
        else
            flash[:errors] = @album.errors.full_messages
            redirect_to band_url(@album.band_name)
        end
    end
    def show
        @album = Album.find_by(id: params[:id])
        render :show
    end

    def edit
        @album = Album.find_by(id: params[:id])
        render :edit
    end

    def destroy
        @album = Album.find_by(id: params[:id])
        @album.destroy
        redirect_to band_url(@album.band_name)
    end
    def update
        @album = Album.find(params[:id])
        if @album.update_attributes(album_params)
            render :show
        else
            flash[:errors] = ["Woah that was whack"]
            render :edit
        end
    end

    private
    def album_params
        params.require(:album).permit(:title, :year, :live?, :band_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?


    def login!(user)
        session[:session_token] = user.reset_session_token!
    end
    
    def current_user
        return nil if session[:session_token].nil?
        User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def logout!

        if logged_in?
            current_user.reset_session_token!
            session[:session_token] = nil
            redirect_to :new_session
        end
    end

    def ensure_logged_in
        flash.now[:error] = ["You must be logged in to do that!"]
        redirect_to :new_session_url unless logged_in?
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def new
        render :new
    end

    def show
        @band = Band.find_by(id: params[:id])
        render :show
    end

    def edit
        render :edit
    end
    
    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    def update
        @band = Band.find(params[:id])
        if @band.update_attributes(parse_band)
            render :show
        else
            flash[:errors] = ["brah your band needs a name dude"]
            render :edit
        end
    end

    def create
        @band = Band.new(parse_band)
        if @band.save
            redirect_to band_url(@band)
        else
            flash[:errors] = ["brah your band needs a name dude"]
            render :new
        end

    end

    def index
        @bands = Band.all
        render :index
    end


    private
    def parse_band
        params.require(:band).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def new #new_session_url GET
        @user = User.new
        render :new
    end

    def create #session_url POST
        @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
        unless @user
            flash.now[:errors] = ['invalid email/password']
            render :new
        else
            login!(@user)
            redirect_to user_url(@user)
        end
    end

    def destroy #session_url DESTROY
        logout!
    end


end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController


    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            render :show
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to :new_user
        end
    end

    def show
        render :show
    end


    private

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


    def render_errors
        if flash[:errors]
            flash[:errors].each{ |error| puts error }
        end
    end

    def authentic
        "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
    end
end

app/views/albums/edit.html.erb
# <section class="page"><div class="centered-box">
#     <h2> Oh you got a new album? </h2>

#     <form method="post" action="<%= bands_url%>">
#         <%= authentic %>
#         <label for="title">Whats it called?</label>
#             <input type="text" name="album[title]" id="title"/>
#             <br>
#             <input type="radio" name="album[live?]" value="false" checked> Studio
#             <input type="radio" name="album[live?" value="true"> Live<br>

#         <input type="submit" value="Time for a release party!"/>
#     </form>
# </div></section>

app/views/albums/index.html.erb
    
    
    <ul>
    <% @albums.each do |album| %>
        <li><a href="<%= album_url(album) %>"><%= album.title %></a></li>
    <% end %>
    </ul>

app/views/albums/new.html.erb
<section class="page"><div class="centered-box">
    <h2> Oh you got a new album? </h2>

    <form method="post" action="<%= albums_url%>">

        <%= authentic %>
            <label for="title">Whats it called?</label>
            <input type="text" name="album[title]" id="title"/>
            <br>
            <input type="radio" name="album[live?]" value="false" checked> Studio
            <input type="radio" name="album[live?]" value="true"> Live
            <br>
            <label for="year">What year did it come out?</label>
            <input type="text" name="album[year]" id="year">
            <br>
            <label for="Band">Who made it?</label>
                <select name="album[band_name]"> 

                    <% Band.all.each do |band| %>
                        <option name="album[band_name]" 
                        value="<%=band.id%>" 
                        <%if band.id == params[:band_id].to_i %> 

                            selected
                        <%end%>> <%=band.name%>
                        </option>
                    <% end %>
                </select>

            
        <input type="submit" value="Time for a release party!"/>
    </form>
</div></section>

app/views/bands/edit.html.erb
<section class="page"><div class="centered-box">
    <h2> Edit Band:</h2>

    <form method="post" action="<%= band_url%>">
        <%= authentic %>
        <input type="hidden" name="_method" value="patch"/>
        <label for="band_name">Type your sick band name!</label>
            <input type="text" name="band[name]" id="band_name"/>
        <input type="submit" value="DUUUDE! this name is WAAY cooler!"/>
    </form>
</div></section>

app/views/bands/index.html.erb
<h2>The Bands!</h2>
<style>
    .bands{
        font-weight: bold;
        background-color: orange;
    }
    .band {
        float: none;
        text-decoration: none;
        text-decoration-color: antiquewhite;
        background-color: royalblue;
        border-radius: 100%;
        font-family: Georgia, 'Times New Roman', Times, serif
        font-size: large;
        color: antiquewhite;
        padding: 5px;
        margin: 4px;  
    }
    ul > li{
        list_style: none;
    }

</style>
<section class="bands">

<%unless @bands.empty? %>
    <ul>
    <% @bands.each do |band| %>
        <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
    <% end %>
    </ul>
<% end %>
</section>
    <a class ="band" href="<%= new_band_url %>">Add a Band!</a>




    

app/views/bands/new.html.erb
<section class="page"><div class="centered-box">
    <h2> New Band</h2>

    <form method="post" action="<%= bands_url%>">
        <%= authentic %>
        <label for="band_name">Type your sick band name!</label>
            <input type="text" name="band[name]" id="band_name"/>
        <input type="submit" value="Duuuuude! sick band name!"/>
    </form>
</div></section>

app/views/bands/show.html.erb
<h1 class="bandname"><%= @band.name%></h1>
<p>This band is dope!</p>

<a href="<%=edit_band_url%>">Edit this band!</a>
<a href="<%=new_band_album_url(@band)%>">New Album</a>
<a href="<%=band_albums_url(@band)%>">Albums by this band</a>

<form method="post" action="<%= band_url %>">
    <%= authentic %>
    <input type="hidden" name="_method" value="DELETE">

    <input type="submit" value="Break up the band :(">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section>
    <h1 id="header"> Music Project </h1>
    <% if logged_in?%>
      <form id="user_nav" method="POST" action=<%= session_url %> >
        <%= authentic %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Log In</a>
      <a href="<%= new_user_url %>">Sign up</a>
    <% end %>
    <br>
    <%= render_errors %>
    <br>
    <a href="<%= bands_url %>">Home</a>
    <img src="https://images.all-free-download.com/images/graphicthumb/music_note_and_people_vector_550935.jpg"
        alt="logo">
    <section>
    <br>
    
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<section class="page"><div class="centered-box">
    <h2> Sign Up</h2>

    <form method="POST" action="<%= users_url %>">
        <%= authentic %>
        <label for="user_email">Email Address</label>
            <input type="text" name="user[email]" id="user_email"/>
        <br>
        <label for ="user_password">Password</label>
            <input type="password" name="user[password]" id="user_password/">
        <br>
            <input type="submit" value="Sign Up!"/>
    </form>
</div></section>

app/views/users/show.html.erb
<h3>it worked</h3>